### ISSUE TITLE
It seems that the new version of ghidra is not supported

### ISSUE THREAD

**Issue by wxcree** [Nalen98/eBPF-for-Ghidra#8]
Extension version for [eBPF-for-Ghidra] is incompatible with Ghidra.
---------------------------------------------------
Build Date: 2022-Jan-25 1526 EST
Ghidra Version: 10.1.2
Java Home: /Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home
JVM Version: Eclipse Adoptium 11.0.14.1
OS: Mac OS X 12.0.1 x86_64

**Comment by wxcree** [comment]
sorry, I found the solution

**Comment by jqgsninimo** [comment]
I got the following error when importing `ghidra_9.2_eBPF-for-Ghidra.zip`:
> Extension version for [ghidra_9.2_eBPF-for-Ghidra.zip] is incompatible with Ghidra.

I solved it as follows:
1. Generate extension
   ```
   git clone https://github.com/Nalen98/eBPF-for-Ghidra.git
   cd eBPF-for-Ghidra
   export GHIDRA_INSTALL_DIR=/Applications/Ghidra
   gradle 
   ```

2. Install extension
   Chidra → File → Install Extensions... → ➕（Add extension）→  Select the file generated in the first step:
   `~/eBPF-for-Ghidra/dist/ghidra_10.1.2_PUBLIC_20220401_eBPF-for-Ghidra.zip`

**Comment by Nalen98** [comment]
Hi! Yeah, I see you use Ghidra 10.1.2 , so Ghidra and plugin versions must be equal ( GHIDRA_INSTALL_DIR env should be path of Ghidra 10.1.2). Your steps are correct.
